let val;
const today = new Date();
console.log(today);
// let birthday = new Date('9-10-1981 11:25:00');
let birthday = new Date('September-10-1981 11:25:00');
birthday = new Date('1/10/1981 11:25:00');
console.log('birthday: ' + birthday);
val = today.getMonth();
console.log('Month ' + val);
val = today.getDate();
console.log(val);
val = today.getDay();
console.log(val);
val = today.getFullYear();
console.log(val);
val = today.getHours();
console.log(val);
val = today.getMinutes();
console.log(val);
val = today.getMonth();
console.log(val);
console.log('----------------');
birthday = new Date('01-01-1900 00:00:00');
// console.log(birthday);
birthday.setMonth(11);
birthday.setDate(11);
birthday.setFullYear(2000);
birthday.setHours(11);
birthday.setMinutes(11);
birthday.setSeconds(25);
console.log(birthday);
